services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: flask
      POSTGRES_PASSWORD: passwordhere
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    networks:
      - blog_network
    volumes:
      - postgres_data:/var/lib/postgresql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  web:
    image: ghcr.io/alexbilla02/strange-blog-app:latest
    ports:
      - "8080:5000"
    networks:
      - blog_network
    environment:
      - FLASK_APP=app.py
      - SQLALCHEMY_DATABASE_URI=postgresql://flask:passwordhere@db:5432/blog
    deploy:
      replicas: 2             
      update_config:
        parallelism: 1
        order: start-first    
        failure_action: rollback 
      restart_policy:
        condition: on-failure

networks:
  blog_network:
    driver: overlay 

volumes:
  postgres_data: 